
public enum Categorias {
	FRUTA, VERDURAS_HORTALIZAS, CARNICERIA, PESCADERIA, CHARCUTERIA, 
	PANADERIA_BOLLERIA_PASTELERIA, APERITIVOS, DULCE, CONSERVAS, ALCOHOLES,
	CERVEZA, VINOS, AGUAS, ELECTRODOMESTICOS, SONIDO, ROPA, MUEBLES
}
